[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.http_headers]
CONTEXT7_API_KEY = "ctx7sk-637dac1d-ee87-409e-9112-1527bbbe0f40"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.clerk]
type = "url"
url = "https://mcp.clerk.com/mcp"

[mcp_servers.zod]
url = "https://mcp.inkeep.com/zod/mcp"

[mcp_servers.stripe]
command = "cmd"
args = ["/c", "npx", "-y", "@stripe/mcp@latest"]
startup_timeout_sec = 30
tool_timeout_sec = 60
enabled = true

[mcp_servers.stripe.env]
STRIPE_SECRET_KEY = "sk_test_51TAXA0Blnu3hh0HdZkh5YKMtD4Z3uxUsUfA63r161jWPPdO2yc1dkLOD2KCgNiiAkrZTuGXx40y26VPWJmPv34ql00Io6zdKPd"    
# STRIPE_SECRET_KEY used in `Droplet` project!!!