import path from "node:path";
import { expect, test, type Page } from "@playwright/test";
import {
  getE2ETestUser,
  missingCredentialsError,
  requireE2ETestUser,
} from "./utils/e2e-test-user";

const authFile = path.join(__dirname, ".clerk/user.json");
const e2eTestUser = getE2ETestUser();

async function ensureAuthenticatedAppPage(page: Page) {
  await page.goto("/app/new", {
    waitUntil: "domcontentloaded",
    timeout: 60_000,
  });

  if (/\/sign-in(?:\/|$|\?)/.test(page.url())) {
    const { identifier, password, username } = requireE2ETestUser();

    await page
      .getByRole("textbox", { name: "Email address or username" })
      .fill(username ?? identifier);
    await page.locator('input[name="password"]').fill(password);
    await page.getByRole("button", { name: "Continue" }).click();
    await page.waitForURL(/\/app(?:\/new)?(?:\?.*)?$/, { timeout: 60_000 });

    if (/\/app(?:\?.*)?$/.test(page.url())) {
      await page.goto("/app/new", {
        waitUntil: "domcontentloaded",
        timeout: 60_000,
      });
    }
  }
}

test.describe("live image generation via chat", () => {
  test.skip(!e2eTestUser, missingCredentialsError);
  test.skip(
    ({ browserName }) => browserName !== "chromium",
    "Live media verification runs only on Chromium.",
  );
  test.skip(
    process.env.RUN_LIVE_MEDIA_TESTS !== "1",
    "Set RUN_LIVE_MEDIA_TESTS=1 to run live media tests.",
  );
  test.use({ storageState: authFile });

  test("generates an image in chat and renders the download proxy URL", async ({
    page,
  }) => {
    test.setTimeout(240_000);
    await ensureAuthenticatedAppPage(page);

    await page
      .getByRole("link", { name: /strategist/i })
      .first()
      .click();
    await expect(page).toHaveURL(/\/app(?:\?.*)?$/);

    const chatInput = page.locator("textarea#chatInput");
    await chatInput.waitFor({ state: "visible", timeout: 30_000 });

    await chatInput.fill(
      "Generate image of a clean blue water droplet icon on white background.",
    );
    await page.getByRole("button", { name: "Send message" }).click();

    const generatedImage = page
      .locator('main.ChatWrapper img[alt="Image generated by Droplet"]')
      .last();

    await generatedImage.waitFor({ state: "visible", timeout: 180_000 });
    const imageSrc = await generatedImage.getAttribute("src");

    expect(imageSrc).toBeTruthy();
    expect(imageSrc).toContain("/api/download?key=");
  });
});
