import classNames from "classnames";
import LoadingBubbles from "./loading-bubbles";
import { useState } from "react";
import Image from "next/image";
import { resolveStoredAssetUrl } from "@/lib/utils/aws/s3-file-reference";

interface ImageHolderProps {
  src: string;
  width: number;
  height: number;
  alt?: string;
  hasTools?: boolean;
}

export default function ImageHolder({
  width,
  height,
  hasTools = false,
  src: imageUrl,
  alt: imageName = "Image generated by Droplet",
}: ImageHolderProps) {
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [isDownloading, setIsDownloading] = useState<boolean>(false);
  const resolvedImageUrl = resolveStoredAssetUrl(imageUrl);
  const downloadUrl = resolveStoredAssetUrl(imageUrl, {
    download: true,
    filename: imageName,
  });

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const response = await fetch(downloadUrl);

      if (!response.ok) {
        throw new Error(`Download failed with status ${response.status}`);
      }

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = imageName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch {
      // Ignore download failures and leave the current image rendered.
    } finally {
      setIsDownloading(false);
    }
  };

  const imageHolderClass = classNames(
    "ImageHolder relative mb-2 mt-3 flex max-h-max max-w-max items-center justify-center overflow-hidden rounded",
    "bg-nightIndigo-500/10 shadow-sm transition-all",
  );

  const imageClass = classNames(
    !isLoading &&
      "animate-fade animate-once animate-duration-500 animate-delay-300 animate-ease-in-out",
    { hidden: isLoading },
  );

  return (
    <div className={imageHolderClass}>
      {isLoading ? (
        <span className="flex p-4">
          <LoadingBubbles size="small" />
        </span>
      ) : (
        hasTools && (
          <button
            type="button"
            className="icon-btn absolute bottom-2 right-2 z-10 bg-black/50 text-white hover:bg-black/60"
            onClick={handleDownload}
            disabled={isDownloading}
            aria-label="Download generated image"
          >
            {isDownloading ? (
              <LoadingBubbles size="small" className="w-auto! gap-0.5" />
            ) : (
              <i className="bi bi-download"></i>
            )}
          </button>
        )
      )}

      <Image
        priority
        unoptimized
        src={resolvedImageUrl}
        width={width}
        height={height}
        loading="eager"
        onLoad={() => setIsLoading(false)}
        onError={() => setIsLoading(false)}
        alt={imageName}
        className={imageClass}
        sizes={`(max-width: 768px) 100vw, (max-width: 1200px) 50vw, ${width}px`}
      />
    </div>
  );
}
